# This is a basic workflow to help you get started with Actions with MATLAB and Python

name: MATLAB Python Action

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  interop:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Sets up MATLAB on a GitHub-hosted runner
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        
      # Sets up Python and dependencies
      - name: Install Python dependencies
        run: python3 -m pip install tiktoken

      # You can use "run-command" to execute custom MATLAB scripts, functions, or statements
      - name: Run MATLAB script
        uses: matlab-actions/run-command@v2
        with:
          command: disp('Calling Python from MATLAB in an Action!'); countTokens
        
